// modals
export const MANAGE_AUTH_MODAL = "MANAGE_AUTH_MODAL";
export const MANAGE_VIDEO_MODAL = "MANAGE_VIDEO_MODAL";
// pages
export const SET_RANKS = "SET_RANKS";
export const SET_GUILDS = "SET_GUILDS";
export const SET_NEWS = "SET_NEWS";
export const SET_DONATE = "SET_DONATE";
export const SET_SHOP = "SET_SHOP";
export const SET_SHOP_LOADING = "SET_SHOP_LOADING";
export const SET_SHOP_ERROR = "SET_SHOP_ERROR";
export const SET_SHOP_MESSAGE = "SET_SHOP_MESSAGE";
// recent
export const SET_RECENT_LOADING = "SET_RECENT_LOADING";
export const SET_RECENT_DATA = "SET_RECENT_DATA";
// init
export const SET_ONLINE = "SET_ONLINE";
// auth
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
// profile
export const SET_PROFILE_DATA = "SET_PROFILE_DATA";
export const CLEAR_PROFILE_DATA = "CLEAR_PROFILE_DATA";
export const CHANGE_USER_BALANCE = "CHANGE_USER_BALANCE";
export const DELETE_CHAR = "DELETE_CHAR";
export const RESURRECT_CHAR = "RESURRECT_CHAR";
export const CHAR_ACTION_LOADING = "CHAR_ACTION_LOADING";
export const CHAR_ACTION_ERROR = "CHAR_ACTION_ERROR";
export const GET_RANK_REWARD = "GET_RANK_REWARD";
export const RANK_REWARD_LOADING = "RANK_REWARD_LOADING";
export const RANK_REWARD_ERROR = "RANK_REWARD_ERROR";
export const GET_SPENDER_REWARD = "GET_SPENDER_REWARD";
export const SET_SPENDER_LOADING = "SET_SPENDER_LOADING";
export const SET_SPENDER_ERROR = "SET_SPENDER_ERROR";
export const INCREASE_SPENDERS_STATUS = "INCREASE_SPENDERS_STATUS";
export const ADD_ROULETTE_REWARD = "ADD_ROULETTE_REWARD";
export const SET_ROULETTE_ERROR = "SET_ROULETTE_ERROR";
export const SET_ROULETTE_STATUS = "SET_ROULETTE_STATUS";
export const SET_ROULETTE_LOADING = "SET_ROULETTE_LOADING";
export const SET_ROULETTE_MESSAGE = "SET_ROULETTE_MESSAGE";